.travis.yml
README.md
requirements.txt
run_travis.sh

This enables Travis CI, which currently builds SMAUG and runs all the tests.

tests: Enable travis CI.

---

smaug/core/scheduler.cpp

We should kick off the scheduling by putting operators to the ready
queue if they don't any pending inputs. The data op shouldn't be taken
specially here.
TESTED=all tests are still passing

core: Fix scheduler.

---

make/Makefile.common
smaug/python/graph.py
smaug/python/unique_name_test.py

When creating a unique name for the operator, the naming format is
"%(name)s_%(idx)d". If the name is already in use, we previously just
increased the idx. For example, if "add" is in use, "add_1" will be
used. However, this could mistakenly return a name already in use
as shown in the following example:
```python
res = add(x, y) # This will be named "add".
res = add(x, y, name="add_1") # This will be named "add_1".
res = add(x, y) # BUG: this will also be named "add_1".
```
To solve this, we keep increasing the idx until the new name is not
in use. In the above example, the third add will now be named "add_2".
This also makes create_unique_name() public, so the user can get a
unique name before the operator is created. Example:
```python
res = add(x, y) # This will be named "add". …
```

python: Fix a bug in creating unique names.

---

smaug/python/graph.py
smaug/python/unique_name_test.py

This fixes a bug in PR #17.
The bug was that `mark_as_used` kwarg of `create_unique_name` would only be checked if the name was already in the set of used names.

python: Fix a bug in create_unique_name.

---

make/Makefile.common
smaug/python/ops/array_ops.py
smaug/python/ops/attention_test.py
smaug/python/ops/fp_precision_test.py
smaug/python/smaug_test.py

The way we model FP16 operations in Aladdin, which converts FP16 to FP32 for
computation and converts the results back to FP16 can potentially lead to
slight precision loss. The aggregated effect can lead to some tests failing
the required accuracy. This adds a test for all the precision-losing operators
against TF operators and also relaxes the required accuracy from 3 decimals to 2
decimals.
This fixes issue #11 .
TESTED=unit

python: Add an FP precision test and relax test accuracy.

---

make/Makefile.common
smaug/python/graph.py
smaug/python/ops/common.py
smaug/python/ops/data_op_test.py

python: Deduplicate data ops.
Previously if multiple operators share the same input tensor, we
would create duplicated data ops. This adds some tracking info to
deduplicate data ops.
TESTED=unit

python: Deduplicate data ops created for input tensors

---

smaug/core/typedefs.h

The graph view of the network didn't allow multiple edges between two vertices.
This leads to inputs unconstructed when multiple operator inputs come from the same
input tensor, because the network builder only set an input for an operator if
there's an in_edge. This fixes the issue by making the boost graph use
std::vector to store the edges (instead of std::set), which thus can represent
multiple edges.

core: Allow boost graph to have multiple edges between two vertices.

---

smaug/operators/smv/smv_softmax_op.cpp

After running all tiles, we need to shuffle the tiles to the original output
tensor.
TESTED=all tests are passing.

smv: Forgot to untile the output tiles after running softmax.

---

smaug/python/ops/fp_precision_test.py

From TensorFlow-2.3, tensorflow.python no longer exposes xxx_ops to the user.
This uses a more standard way of calling TF's APIs.
TESTED=all tests are passing.

tests: Use new TensorFlow API calls.

---

.circleci/config.yml

The VCPU provided by CircleCI has 2 threads per core. This reduces the CI build
from 10 mins to 7 mins (the SMAUG build reduces to 3.5 mins from 6.5 mins).

tests: Use 4 threads in CircleCI build.

---

smaug/__init__.py
smaug/python/create_model_example.py
smaug/python/global_vars.py
smaug/python/ops/activation_ops.py
smaug/python/ops/activation_ops_test.py
smaug/python/ops/nn.py
smaug/python/ops/nn_ops.py
smaug/python/ops/recurrent.py

This makes the Python API easier to use. For example, previously the Python code
looks like:
```python
import numpy as np
from smaug.python.ops import array_ops, data_op, math_ops, nn_ops
from smaug.python.tensor import Tensor
from smaug.python.graph import Graph
from smaug.core import types_pb2
with Graph():
x = Tensor(layout=types_pb2.NC, tensor_data=np.array())
x = data_op.input_data(x)
y = math_ops.add(x, x)
z = array_ops.flatten(y)
u = nn_ops.matmul(..., activation=types_pb2.ReLU)
```
Now it becomes:
```python
import numpy as np
import smaug as sg
with sg.Graph():
x = sg.Tensor(layout=sg.NC, tensor_data=np.array())
x = sg.input_data(x)
y = sg.math.add(x, x)
z = sg.flatten(y)
u = sg.nn.matmul(..., activation=sg.ReLU)
```
This fixes issue #31.

python: Simplify Python module naming for easier usage.

---

smaug/core/datatypes.h

This class is no longer used since all the data transformation ops are
done in Python.

core: Remove DataLayoutSet.

---

.circleci/config.yml
make/Makefile.common
make/Makefile.native
smaug/core/datatypes.h

Currently, these files were being generated directly into the source
code tree itself, which is not the right place for generated code.

make: Generate proto files directly into the build dir.

---

Doxyfile

We're planning to use Sphinx to generate Python docs.

Exclude Python and SMAUGv1 code from Doxygen.

---

.circleci/config.yml

This is only enabled when merging PRs into harvard-acc master branch. We
don't want docs to be deployed when testing PRs or on anyone else's
personal CircleCI account. On the other hand, we don't want CircleCI
workflows to fail for them either. This is accomplished as follows:
1. Separate the process into a build/test job and a docs deploy job.
2. The docs deploy job is only run on master branches.
3. The CircleCI project must not set the env var ENABLE_DOC_DEPLOY=1
unless it is the deployment project.
4. The GitHub deploy SSH key, which is required to submit changes to the
repository, is only registered in the harvard-acc CircleCI account.

Automatically generate and deploy Doxygen documentation.

---

.circleci/config.yml

CircleCI runs all its bash commands with -eo pipefail, so any command
that returns a non-zero exit code will cause the job to fail. In this
case, git-diff will return 1 if there are diffs. The solution is to
ignore git-diff and just create a commit, swallowing the exit code
(which is 1 if there are no diffs). If there is no diff, there will be
no commit, but git push will still return 0.

Remove git-diff detection logic.

---

docs/Makefile
docs/source/Doxyfile
docs/source/conf.py
docs/source/index.rst

Sphinx + Breathe + Exhale is too complicated of a pipeline, and while
they look more a bit more modern, Doxygen's presentation is more useful.
Python tutorials will be written in rst, and C++ tutorials will be
written in Markdown.

Use Doxygen for C++ API documentation instead of Sphinx.

---

docs/Makefile
docs/source/Doxyfile
docs/source/conf.py
docs/source/index.rst
smaug/core/datatypes.h
smaug/core/tensor.h
smaug/operators/batch_norm_op.h
smaug/operators/concat_op.h
smaug/operators/control_flow_ops.h
smaug/operators/convolution_op.h
smaug/operators/data_op.h
smaug/operators/depthwise_convolution_op.h
smaug/operators/eltwise_add_op.h
smaug/operators/eltwise_mul_op.h
smaug/operators/eltwise_op.h
smaug/operators/elu_op.h
smaug/operators/fused_activation_op.h
smaug/operators/greater_op.h
smaug/operators/inner_product_op.h
smaug/operators/less_op.h
smaug/operators/pooling_op.h
smaug/operators/relu_op.h
smaug/operators/reorder_op.h
smaug/operators/repeat_op.h
smaug/operators/reshape_op.h
smaug/operators/sigmoid_op.h
smaug/operators/softmax_op.h
smaug/operators/split_op.h
smaug/operators/tanh_op.h
smaug/operators/unary_op.h

This produces a short description of the method/class/variable in the
listing, and only if a more detailed description exists will a larger
block for it be generated further down. This is mostly automatic, but
sometimes Doxygen needs a bit more help.
Also, removes the ugly DOXYGEN_SHOULD_SKIP_THIS macro - this was only
used for Exhale.

Add brief descriptions for everything

---

.circleci/config.yml
.circleci/run_simulation_sweeps.py
.circleci/sweep.json
docker/Dockerfile

We previously added the support in CircirCI for downloading the latest
gem5 binary from gem5-aladdin repo, but didn't actually use the
downloaded binary. This invokes the SMAUG sweep generator and runs the
generated sweeps using the downloaded gem5 binary.
We currently sweep the number of accelerators (1-4) and the SoC interface
choices (DMA or ACP). Because our current CircleCI plan only has 4GB
memory, we can only run one simulation at a time in order to not go OOM.

tests: Add simulation sweeps in CircleCI build.

---

docs/source/intro.dox
smaug/core/operator.h
smaug/operators/convolution_op.h
smaug/utility/fp16_utils.h

This adds a basic landing page for the C++ API site, an overview of
the execution flow, and partial instructions for building a custom operator.
Issue #4

docs: Add overview of C++ API and building a custom operator

---

smaug/core/operator.h

createAllTensors() used to be called by the C++ network builder, but now
all of that logic is handled on the Python side, written into the
network topology proto, and all tensors are created in the network
builder directly. However, unit tests still call this function, so we
leave it as an option, but mark that it's only for testing purposes.

operator: createAllTensors() is only used by tests.

---

smaug/core/operator.cpp
smaug/core/operator.h

The validateInputsOutputs only checks if the tensors have been constructed and allocated storage, but in practice, this is already handled by network_builder (and tested by network_test), and operators which override validate() currently don't call the super-method anyways. In my opinion, it's an extraneous check that we can do away with.

 operators: Clean up operator validation APIs.

---

docs/source/intro.dox

As a software-only implementation, this leaves out any details on
DMA/array address mapping/etc. Those will be dealt with in the next
section.

docs: Add example of SW-implementation for a custom operator.

---

smaug/core/backend.h
smaug/smaug.cpp

This makes all the backends consistent, so it's easier to explain and
add global hooks for the tutorial.

backend: Add initGlobals() for ReferenceBackend too.

---

README.md

To prevent OOM, drop the default recommended build parallelism to 2
cores.

Add warning about parallel builds potentially causing OOM.

---

smaug/core/tensor_utils.cpp
smaug/core/tensor_utils.h
smaug/operators/smv/smv_batch_norm_tiling.cpp
smaug/operators/smv/smv_batch_norm_tiling_test.cpp
smaug/operators/smv/smv_convolution_tiling.cpp
smaug/operators/smv/smv_convolution_tiling_test.cpp
smaug/operators/smv/smv_eltwise_add_op.cpp
smaug/operators/smv/smv_eltwise_mul_op.cpp
smaug/operators/smv/smv_greater_op.cpp
smaug/operators/smv/smv_inner_product_tiling.cpp
smaug/operators/smv/smv_inner_product_tiling_test.cpp
smaug/operators/smv/smv_less_op.cpp
smaug/operators/smv/smv_pooling_tiling.cpp
smaug/operators/smv/smv_pooling_tiling_test.cpp
smaug/operators/smv/smv_unary_op_common.cpp
smaug/operators/smv/smv_unary_op_common.h
smaug/operators/smv/smv_unary_tiling_test.cpp

The goal is to simplify the tiling APIs, rename them to be more clear,
and remove redundant functions.
* The generateTiledTensorAndCopyData function has been deleted.
* Some unary/elementwise tiling functions are moved to tensor_utils.h.
* generateTiledTensor renamed to
generateTiledTensorWithStrideAndPadding. A convenience function that
takes no stride or padding parameters is also provided.

core: Reorganize some tiling functions for easier API reuse.

---

docs/source/Doxyfile
docs/source/intro.dox

This goes through all the steps:
1. Creating scratchpads for local use.
2. Tiling tensors with the tiling library functions.
3. Writing a loop nest.
4. Modifying code to work with gem5-aladdin APIs.
5. Modifying code for LLVM-Tracer.
This does not include instructions for actually running a simulation.
That's more broadly useful information which should go somewhere else
(maybe on the Python side).

docs: Add documentation for writing the HW-accelerator operator.

---

docs/source/intro.dox
docs/source/tiling.dox
smaug/operators/smv/smv_convolution_op.h

Some of the text is pulled from the paper, but each section usually has
some code examples to illustrate how the APIs are used.

docs: Add a page dedicated to tiling optimizers.

---

docs/source/add_python_operator.rst
docs/source/build_python_model.rst
docs/source/index.rst
docs/source/python_api.rst
docs/source/python_tutorials.rst

This adds two placeholders for Python side tutorials.
1. Building a new model with Python APIs.
2. Adding a new Python operator.

docs: Add a few RST files for tutorials on the Python side.

---

docs/source/add_python_operator.rst
docs/source/smaug.rst
smaug/__init__.py

The last step of adding a new operator is to import it into the top level
smaug module. Getting Sphinx to generate a link to the smaug autodoc
section required adding additional docstrings and a dummy function
(which isn't displayed anywhere on the documentation site).

docs: Add text to expose new operator in the smaug module.

---

docs/source/cpp_docs.rst
docs/source/index.rst
docs/source/python_api.rst
docs/source/python_tutorials.rst

A few cosmetics are added to make the docs page a bit nicer:
1) Add a sidebar entry for the C++ docs.
2) Increase the toctree depth visibility of the main page.
3) Reorganize the internal modules into the SMAUG Python APIs.

docs: Add a few cosmetics on the tree structure.

---

docs/source/tutorial.dox

Catch2 test cases require an additional third parameter which can be
used to group tests together.

Fix bug in tutorial documentation.
